sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ofsyYntG2YNjRiyYhvkKQY+MiSQaL9XysdfdvR4ZHZ9IIihcmv/G021TR/xoTEsdfBSLMhlYqCvTN0nxzCnNRxFAxcpjuJP9dRteSsxrId/olyLFqpGw+xWY7i/79q+0T/xb+WmpNfCkw2r+Yvffa/9x619BLRfzIvxIlHL/YFW2RbUTmpE5iuI8vwje3OpuSZpxj8oFxo9CV+iR9PAhuwgbXfi4ILh3Y9Xs8iW1EqB3ak1k9X+xL5bpr0gLKp5XOE//iHq7C+tQCqD4w5ffVOD64kCrFRr5++f5CkBWXCJXalXUQeMgBgGUKXPoR8sb41KbhJBYA7wWL9IqIOb/punZj8ckSziYk3oA0cPzp+Vlyj72xqm9uya10WkYy9kiulWVYHobfstBNGISPVQ3p1BrI12B2yALmZy69s3G1uTad0TtB5NaaDTMbN5AE5rpWuxSKdtaiRGPCFNOMTT+9o/F/TeEMr4bn89FiDOyy5Rnh3AkxLQtUy2eCWPEhxjfiJXjULsRtH87SzzVRy6g8agrE4jcJDc6MS4qXLiXn6ANAvmBlJp9iPgVACOVn2AqOapv19AY/EvpNX1ka7WoNvVUGRn9W81jQdktTuLdntkBjQw9F8RG5tmYpBN0pQv67L0WERbz2q68K2L4h2smVKFZvOQgeegFXB93G7c4YYM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/The-Federalist-Papers_1404
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy